Tekton create git release and populate with artifacts
AICoE/aicoe-ci pull request #119
Opened 2021-07-08 23:40 UTC by Gregory-Pereira

## Related Issues and Dependencies

Still needs testing, I have provided my example task runs to the pr for use in testing. Can be removed after.

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements
Added in 2 tasks to create a release from an existing tag and then populate that release with artifacts generated
## Description

2021-07-08 23:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Faicoe-ci).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/aicoe-ci/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-07-13 21:19 UTC, goern commented
looks good!! nice work. I wonder, if there is something from upstream tekton catalog we can reuse?

2021-09-08 18:26 UTC, harshad16 requested changes
Follow the comments same as #129 
thanks :100:

2021-09-08 18:26 UTC, harshad16 commented on greg/greg-issue-binding.yaml
> +apiVersion: triggers.tekton.dev/v1alpha1
drop the greg dir

2021-09-16 21:04 UTC, Gregory-Pereira commented
Opening new PR from feature branch.

2021-09-16 21:04 UTC, closed without merging