creating environments pipeline to run tag deploy for each deployment environmet
AICoE/aicoe-ci pull request #179
Opened 2022-06-14 16:19 UTC by Gregory-Pereira

## Related Issues and Dependencies

Addresses: https://github.com/AICoE/aicoe-ci/issues/176

## This introduces a breaking change

- [x] Yes --> change how tag-deploy tasks work and structure of the `.aicoe-ci.yaml` file
- [ ] No

Anything that utilizes the old structure of .aicoe-ci.yaml file will no longer function because the deploy section now has different environments rather than the deployment variables.

## Description

Created a pipeline as task (similar to overlay pipeline) that will allow sesheta to make version bumps and changes as pull request instead of simply pushing to master branch.
/cc @harshad16

2022-06-14 16:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **gregory-pereira** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Faicoe-ci).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/aicoe-ci/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gregory-pereira"]} -->

2022-06-21 04:44 UTC, harshad16 requested changes
we need to make a few changes for this to work
On another note, we want to start with the tag pipeline and then we can work through pr-pipeline.

2022-06-21 04:44 UTC, harshad16 commented on tasks/configuration-task.yaml
> +            write_to_file(f"/tekton/results/deploy", conf, "deploy")
lets do the checking inside the loop.
```
for env in conf.get("deploy", {}):
    if isinstance(conf["deploy"].get(env), str) :
       then keep the same as we had
    elif isinstance(conf["deploy"].get(env), dict):
       if len(conf["deploy"].keys()) > 1:
           output = open(f"/tekton/results/{ele}", "w+")
           json.dump(conf["deploy"].get(ele), output)
           output.close()
      else:
            write the single env bits to the deploy results.
```

2022-06-21 04:44 UTC, harshad16 commented on tasks/environments-pipeline.yaml
> +  name: environments-pipeline
lets have this as `tag-multi-delivery`

2022-06-21 04:44 UTC, harshad16 commented on tasks/environments-pipeline.yaml
> +                    spec_params.append(param)
This is only looping through deploy, we want to loop from the elements in the deploy, need extra loop

2022-06-24 17:42 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | b0d504e93e7689df507503b090787d9309845e72 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_aicoe-ci/179/pre-commit/1540389577255030784) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=aicoe-ci&pr=179). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/AICoE/aicoe-ci/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-28 16:10 UTC, harshad16 requested changes
lgtm for the second round of review
please address the following suggestions.

2022-06-28 16:10 UTC, harshad16 commented on pipeline/pull-request-pipeline.yaml
> +    - name: run-tags-multi-delivery
Please remove this taskruns from `pull-request-pipeline` as we wont be supporting updating multiple overlays for deploy on pull request stage.
Please move it to `tag-release-pipeline`

2022-06-28 16:10 UTC, harshad16 commented on pipeline/tag-release-pipeline.yaml
> +    if not multiple environments
seems like a comment is left , without comment syntax
will update it with proper working and syntax

2022-06-28 16:10 UTC, harshad16 commented on pipeline/tag-release-pipeline.yaml
> +          value: $(tasks.pr-configuration.results.registry)
These params wouldn't be available on pipeline level.
we would be extracting them in the task. 
please remove them.

2022-06-28 16:10 UTC, harshad16 commented on tasks/environments-pipeline.yaml
> +                pipelinerun["spec"]["params"] = spec_params
please test this follow, it seems like it would need to be inside the loop of the taskrun.

2022-06-28 16:10 UTC, harshad16 commented on tasks/pr-config.yaml
> +            if is string:
seems like comment is left.
please convert it into proper code.

2022-06-28 17:29 UTC, Gregory-Pereira commented on tasks/configuration-task.yaml
> +    - name: deploy-info
This was intended as a way  to hold the deployment information if there was only 1 enviornment, however this is not needed as you poinited out.

2022-07-13 17:59 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | f3a5f5f15065be898bdcf77117a2b3205245c16f | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_aicoe-ci/179/pre-commit/1547278429437562880) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=aicoe-ci&pr=179). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/AICoE/aicoe-ci/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-08-01 06:02 UTC, harshad16 requested changes
kudos to the effort
thanks for all the work.
Dropped few comments.
lets address them

2022-08-01 06:02 UTC, harshad16 commented on tasks/tag-multi-delivery.yaml
> +      description: The Number of different environmnets from which to generate a taskrun.
declare the build block params
```
        - name: default_branch
        - name: registry
        - name: registry_org
        - name: registry_project
```

2022-08-01 06:02 UTC, harshad16 commented on tasks/tag-multi-delivery.yaml
> +                value:
set the value from params
`$(params.registry)`
same for the others.

2022-08-02 16:04 UTC, Gregory-Pereira commented on tasks/pr-config.yaml
> +                environment_count = environment_count + 1
It is being used to trigger the task itself guarded by the `when` condition, see: https://github.com/AICoE/aicoe-ci/pull/179/files#diff-368bdb8cf3dbcbe96d0a071d342df9341087568ee1c8699c837ce97b6e3c553dR248-R250 in the pull request pipeline

2022-08-29 14:25 UTC, Gregory-Pereira commented
Next steps to get his approved / merged is to test this with overlay pipeline

2022-11-27 17:24 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2022-11-29 11:24 UTC, goern commented
any update on this?

2022-11-29 14:16 UTC, harshad16 commented
It is blocked by me,
i needed to test this out. 
currently out of cycle , will get this in soon.

2023-02-28 09:23 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2023-03-30 09:24 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2023-04-29 09:27 UTC, sesheta commented
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close

2023-04-29 09:27 UTC, closed without merging

2023-04-29 09:27 UTC, sesheta commented
@sesheta: Closed this PR.

<details>

In response to [this](https://github.com/AICoE/aicoe-ci/pull/179#issuecomment-1528732664):

>Rotten issues close after 30d of inactivity.
>Reopen the issue with `/reopen`.
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>